### ISSUE TITLE
Compile problem with GCC 9.1.1

### ISSUE THREAD

**Issue by GabVenturato** [lucageatti/BLACK#1]
When I try to compile with GCC 9.1.1 I get the following error:

```
$ make
[  9%] Built target remotery
[ 13%] Building CXX object external/fmt/CMakeFiles/fmt.dir/src/format.cc.o
In file included from /home/gabriele/programs/BLACK/external/fmt/include/fmt/format-inl.h:11,
                 from /home/gabriele/programs/BLACK/external/fmt/src/format.cc:8:
/home/gabriele/programs/BLACK/external/fmt/include/fmt/format.h:3620:55: error: ISO C++ did not adopt string literal operator templates taking an argument pack of characters [-Wpedantic]
 3620 | FMT_CONSTEXPR internal::udl_formatter<Char, CHARS...> operator""_format() {
      |                                                       ^~~~~~~~
make[2]: *** [external/fmt/CMakeFiles/fmt.dir/build.make:63: external/fmt/CMakeFiles/fmt.dir/src/format.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: external/fmt/CMakeFiles/fmt.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by nicola-gigante** [comment]
Thanks for reporting it! 

The external library `fmtlib` had to be updated to compile with `gcc` 9. Now it should work on Fedora 30 (tested on Docker).
